<a href="https://colab.research.google.com/github/Saeed-Akbari/CS5783-MachineLearning/blob/main/Assignment3/problem3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Part1.** What are the dimensions of the input and the kernel (or filter)? How many parameters are there in the kernel f?

Input Size: (C,H,W), Kernel Size
C: number of channels,
H: height,
W: width

Input size: (1,6,6),
Kernel size: (1,3,3)

Number of parameters is $10=(3*3*1+1)*1$

**Part2.** What is the output activation map when you apply the convolutional operation using the filter f on the input X without padding?

Below cells

**Part3.** What is the output when you apply a max-pooling operation on the output from the previous question?

Below cells

In [ ]:
import torch
import torch.nn.functional as F

In [ ]:
# By using pytorch built-in functions conv2d and MaxPool2d

f = torch.Tensor([[[[1, 0, -1], [2, 0, -2], [1, 0, -1]]]])
X = torch.Tensor([[[[7, 5, 0, 0, 3, 2], [6, 4, 5, 1, 4, 8], [9, 0, 2, 2, 5, 4], [6, 3, 4, 7, 9, 8], [5, 7, 5, 6, 9, 0], [7, 9, 0, 8, 2, 3]]]])
output1 = F.conv2d(X, f)

max_pool = torch.nn.MaxPool2d(2)
output2 = max_pool(output1)
print('The output after applying the filter:')
print(output1)
print('The Output of max-pooling appleid to the first output:')
print(output2)
print('Number of parameters:')
print((3*3*1+1)*1)

The output after applying the filter:
tensor([[[[ 16.,   9.,  -4., -18.],
          [ 17.,  -5., -10., -12.],
          [ 11.,  -9., -17.,   2.],
          [  9.,  -1., -15.,  16.]]]])
The Output of max-pooling appleid to the first output:
tensor([[[[17., -4.],
          [11., 16.]]]])
Number of parameters:
10


In [ ]:
# Without using pytorch built-in functions conv2d and MaxPool2d

f = torch.Tensor([[1, 0, -1], [2, 0, -2], [1, 0, -1]])
X = torch.Tensor([[7, 5, 0, 0, 3, 2], [6, 4, 5, 1, 4, 8], [9, 0, 2, 2, 5, 4], [6, 3, 4, 7, 9, 8], [5, 7, 5, 6, 9, 0], [7, 9, 0, 8, 2, 3]])

output1 = torch.zeros((4,4))
for i in range(4):
  for j in range(4):
    output1[i,j] = torch.sum(X[i:3+i,j:3+j] * f)

output2 = torch.zeros((2,2))
for i in range(2):
  for j in range(2):
    output2[i,j] = torch.max(output1[2*i:2+2*i,2*j:2+2*j])

print('The output after applying the filter:')
print(output1)
print('The Output of max-pooling appleid to the first output:')
print(output2)
print('Number of parameters:')
print((3*3*1+1)*1)

The output after applying the filter:
tensor([[ 16.,   9.,  -4., -18.],
        [ 17.,  -5., -10., -12.],
        [ 11.,  -9., -17.,   2.],
        [  9.,  -1., -15.,  16.]])
The Output of max-pooling appleid to the first output:
tensor([[17., -4.],
        [11., 16.]])
Number of parameters:
10
